imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# CKEditor Configuration
ivory_ck_editor:
    default_config: my_config
    configs:
        my_config:
            toolbar:                [ [ 'Bold','Italic','Underline','Strike', "-", 'BulletedList','-','Outdent','Indent','-','Blockquote','-','Styles','Format','Font','FontSize','-','TextColor','BGColor', '-','RemoveFormat', '-', 'Link', '-', 'Maximize' ] ]
            uiColor:                "#EEEEEE"

hwi_oauth:
    firewall_name: secured_area
    http_client:
        proxy: %oauth.proxy%
        timeout: %oauth.timeout%
    resource_owners:
        google:
            type:                google
            client_id:           %google_client_id%
            client_secret:       %google_secret%
            scope:               "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
            paths:
                email:           email
                profilepicture:  picture
            options:
                hd: blablacar.com

vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix:         uploads/projects
            upload_destination: %kernel.root_dir%/../web/uploads/projects
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
