security:
    providers:
        in_memory:
#            memory: ~
            memory:
                users:
                    chomb:
                        password: 123123
                        roles: 'ROLE_USER'
                    admin:
                        password: 123123
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }