parameters:
    app.base.class: AppBundle\Base\BaseService
    app.user.provider.class: AppBundle\Security\UserProvider
    app.mail.class: AppBundle\Services\Mail
    app.slack.class: AppBundle\Services\Slack

services:
    app.base:
        class: %app.base.class%
        abstract: true
        calls:
          - [setContainer, [@service_container]]

    app.user.provider:
        class: %app.user.provider.class%
        arguments: [@doctrine, 'AppBundle\Entity\UserGoogle', { google: googleId }, 'default']

    app.mail:
        class: %app.mail.class%
        parent: app.base

    app.slack:
        class: %app.slack.class%
        parent: app.base
