parameters:
    app.base.class: AppBundle\Base\BaseService
    app.user.provider.class: AppBundle\Security\UserProvider
    app.mail.class: AppBundle\Services\Mail
    app.slack.class: AppBundle\Services\Slack
    app.twig_extension.class: AppBundle\Twig\AppExtension
    app.routing.class: AppBundle\Services\Routing
    pagerfanta.view.light.class: AppBundle\Pagerfanta\View\LightView
    pagerfanta.template.light.class: AppBundle\Pagerfanta\Template\LightTemplate

services:
    app.base:
        class: %app.base.class%
        abstract: true
        calls:
          - [setContainer, [@service_container]]

    app.user.provider:
        class: %app.user.provider.class%
        arguments: [@doctrine, 'AppBundle\Entity\UserGoogle', { google: googleId }, 'default']

    app.mail:
        class: %app.mail.class%
        parent: app.base

    app.slack:
        class: %app.slack.class%
        parent: app.base

    app.twig_extension:
        class: %app.twig_extension.class%
        public: false
        arguments: [ %twig.photo.provider.url% ]
        calls:
          - [setContainer, ["@service_container"]]
        tags:
          - { name: twig.extension }

    app.routing:
        class: '%app.routing.class%'
        parent: app.base

    pagerfanta.view.light:
        class: '%pagerfanta.view.light.class%'
        public: false
        arguments: ['@pagerfanta.template.light']
        tags:
            - { name: pagerfanta.view, alias: light }

    pagerfanta.template.light:
        class: '%pagerfanta.template.light.class%'
        public: false
        arguments: ['@translator']
